-- Makati Human Milk Bank Management System
-- Canonical Supabase/PostgreSQL schema — v2
--
-- Changes from v1:
--   + lab_results.recorded_by_name text  (was missing from deployed schema)
--   - discarded_batches_need_reason CHECK constraint dropped
--       The apply_lab_result_to_batch trigger already supplies a reason on lab failure.
--       Admin-initiated discards should not be blocked by a missing free-text field.
--   - supsup_requires_consent_for_pass CHECK constraint dropped
--       Counseling/interview/consent timestamps are not yet captured in the frontend.
--       Re-add when the screening workflow is extended to include those steps.
--   - inquiry_status_timestamp_alignment CHECK constraint replaced by a BEFORE UPDATE
--       trigger (set_inquiry_status_timestamps) that auto-sets the timestamp, so the
--       frontend never has to supply it explicitly.
--   - inventory_summary and available_bottles_fifo views removed
--       Inventory and bottle selection are queried directly from batches/bottles.
--       Views can be re-added if a reporting layer needs them.
--
-- Invariants that remain:
--   + beneficiary_has_contact (contact_number OR contact_email required)
--   + confirmed_dispensing_requires_gate (all verification flags + dispensed_by required)
--   + waiting_list_requires_nicu (only NICU-confirmed inquiries reach waiting/notified)
--   + prevent_invalid_batch_status_transition trigger
--   + prevent_collection_daily_limit_excess trigger
--   + Full audit trail via write_audit_log triggers

begin;

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- Shared helpers
-- ---------------------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- Profiles
-- ---------------------------------------------------------------------------

create table public.profiles (
  id         uuid        primary key references auth.users(id) on delete cascade,
  email      text        not null unique,
  full_name  text        not null,
  role       text        not null check (role in ('admin', 'staff')),
  is_active  boolean     not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_email_normalized check (email = lower(email))
);

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

comment on table public.profiles is
  'Application profile for Supabase auth.users. Role is limited to admin/staff.';

create or replace function public.current_profile_is_admin()
returns boolean
language sql stable security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin' and is_active = true
  );
$$;

create or replace function public.current_profile_is_staff()
returns boolean
language sql stable security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role in ('admin', 'staff') and is_active = true
  );
$$;

-- ---------------------------------------------------------------------------
-- Donors
-- ---------------------------------------------------------------------------

create table public.donors (
  id               uuid        primary key default gen_random_uuid(),
  dtn_number       bigint      generated by default as identity unique,
  dtn              text        generated always as ('DTN-' || lpad(dtn_number::text, 6, '0')) stored unique,
  full_name        text        not null,
  date_of_birth    date,
  address          text        not null,
  contact_number   text,
  email            text,
  occupation       text,
  civil_status     text        check (civil_status in ('single', 'married', 'separated', 'widowed')),
  classification   text        not null check (classification in ('community', 'private', 'institutional')),
  primary_program  text        not null check (primary_program in ('supsup_todo', 'milky_way', 'moms_act')),
  screening_status text        not null default 'pending'
                               check (screening_status in ('pending', 'passed', 'failed', 'not_required')),
  is_active        boolean     not null default true,
  notes            text,
  created_by       uuid        references public.profiles(id) on delete restrict,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  constraint donors_contact_number_shape check (
    contact_number is null or contact_number ~ '^[0-9+() -]{7,20}$'
  ),
  constraint donors_email_normalized check (email is null or email = lower(email))
);

create index donors_program_idx         on public.donors(primary_program);
create index donors_screening_status_idx on public.donors(screening_status);
create index donors_name_search_idx     on public.donors using gin (to_tsvector('simple', full_name));

create trigger donors_set_updated_at
before update on public.donors
for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Donor screenings
-- ---------------------------------------------------------------------------
-- Note: supsup_requires_consent_for_pass constraint has been removed.
--   Re-add when the frontend captures counseling/interview/consent timestamps.

create table public.donor_screenings (
  id                              uuid        primary key default gen_random_uuid(),
  donor_id                        uuid        not null references public.donors(id) on delete restrict,
  program                         text        not null check (program in ('supsup_todo', 'milky_way', 'moms_act')),
  screening_result                text        not null check (screening_result in ('pending', 'passed', 'failed', 'not_required')),
  travel_history_5_years          boolean,
  tuberculosis_history            boolean,
  hepatitis_b_history             boolean,
  mastitis_history                boolean,
  syphilis_history                boolean,
  herpes_or_std_history           boolean,
  blood_transfusion_last_12_months boolean,
  organ_transplant_history        boolean,
  alcohol_last_24_hours           boolean,
  smoking_history                 boolean,
  illegal_drug_use                boolean,
  strict_vegan_diet               boolean,
  current_medications             text,
  last_delivery_date              date,
  counseling_completed_at         timestamptz,
  interview_completed_at          timestamptz,
  consent_signed_at               timestamptz,
  screened_by                     uuid        references public.profiles(id) on delete restrict,
  screened_at                     timestamptz not null default now(),
  notes                           text,
  created_at                      timestamptz not null default now(),
  updated_at                      timestamptz not null default now()
);

create index donor_screenings_donor_idx on public.donor_screenings(donor_id);

create trigger donor_screenings_set_updated_at
before update on public.donor_screenings
for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Collections, batches, and batch-collection links
-- ---------------------------------------------------------------------------

create table public.collections (
  id                   uuid        primary key default gen_random_uuid(),
  ctn_number           bigint      generated by default as identity unique,
  ctn                  text        generated always as ('CTN-' || lpad(ctn_number::text, 6, '0')) stored unique,
  donor_id             uuid        not null references public.donors(id) on delete restrict,
  program              text        not null check (program in ('supsup_todo', 'milky_way', 'moms_act')),
  collection_mode      text        not null check (collection_mode in ('field_collection', 'pickup')),
  collection_point     text,
  collected_at         timestamptz not null,
  pickup_at            timestamptz,
  volume_ml            integer     not null check (volume_ml between 30 and 240),
  age_of_baby_days     integer     check (age_of_baby_days is null or age_of_baby_days >= 0),
  cold_chain_verified  boolean     not null default false,
  collected_by         uuid        references public.profiles(id) on delete restrict,
  notes                text,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);

create index collections_donor_collected_idx   on public.collections(donor_id, collected_at);
create index collections_program_collected_idx on public.collections(program, collected_at);

create trigger collections_set_updated_at
before update on public.collections
for each row execute function public.set_updated_at();

-- Enforce 800 mL/day per donor
create or replace function public.prevent_collection_daily_limit_excess()
returns trigger
language plpgsql
as $$
declare
  day_total integer;
begin
  select coalesce(sum(volume_ml), 0)
  into   day_total
  from   public.collections
  where  donor_id    = new.donor_id
    and  collected_at::date = new.collected_at::date
    and  id <> coalesce(new.id, '00000000-0000-0000-0000-000000000000'::uuid);

  if day_total + new.volume_ml > 800 then
    raise exception 'daily collection limit exceeded: donor % would reach % mL',
      new.donor_id, day_total + new.volume_ml;
  end if;

  return new;
end;
$$;

create trigger collections_prevent_daily_limit_excess
before insert or update of donor_id, collected_at, volume_ml on public.collections
for each row execute function public.prevent_collection_daily_limit_excess();

create table public.batches (
  id               uuid        primary key default gen_random_uuid(),
  batch_number_seq bigint      generated by default as identity unique,
  batch_number     text        generated always as ('BATCH-' || lpad(batch_number_seq::text, 6, '0')) stored unique,
  status           text        not null default 'raw' check (
                               status in (
                                 'raw', 'pre_testing', 'pre_test_passed',
                                 'pasteurized', 'post_testing',
                                 'ready', 'dispensed', 'discarded'
                               )),
  program          text        not null check (program in ('supsup_todo', 'milky_way', 'moms_act', 'mixed')),
  total_volume_ml  integer     not null default 0 check (total_volume_ml >= 0),
  -- discarded_reason is informational only; no longer enforced by a CHECK constraint.
  -- The apply_lab_result_to_batch trigger sets it automatically on lab failure.
  discarded_reason text,
  expires_at       timestamptz,
  created_by       uuid        references public.profiles(id) on delete restrict,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create index batches_status_idx     on public.batches(status);
create index batches_program_idx    on public.batches(program);
create index batches_expires_at_idx on public.batches(expires_at);

create trigger batches_set_updated_at
before update on public.batches
for each row execute function public.set_updated_at();

-- Enforce valid status transitions
create or replace function public.prevent_invalid_batch_status_transition()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' or new.status = old.status then
    return new;
  end if;

  case old.status
    when 'raw'            then if new.status in ('pre_testing', 'discarded')    then return new; end if;
    when 'pre_testing'    then if new.status in ('pre_test_passed', 'discarded') then return new; end if;
    when 'pre_test_passed' then if new.status in ('pasteurized', 'discarded')   then return new; end if;
    when 'pasteurized'    then if new.status in ('post_testing', 'discarded')   then return new; end if;
    when 'post_testing'   then if new.status in ('ready', 'discarded')          then return new; end if;
    when 'ready'          then if new.status in ('dispensed', 'discarded')      then return new; end if;
    when 'dispensed'      then raise exception 'batch status dispensed is terminal';
    when 'discarded'      then raise exception 'batch status discarded is terminal';
    else null;
  end case;

  raise exception 'invalid batch status transition from % to %', old.status, new.status;
end;
$$;

create trigger batches_prevent_invalid_status_transition
before update of status on public.batches
for each row execute function public.prevent_invalid_batch_status_transition();

create table public.batch_collections (
  batch_id      uuid        not null references public.batches(id) on delete restrict,
  collection_id uuid        not null references public.collections(id) on delete restrict,
  volume_ml     integer     not null check (volume_ml > 0),
  created_at    timestamptz not null default now(),
  primary key (batch_id, collection_id)
);

create index batch_collections_collection_idx on public.batch_collections(collection_id);

comment on table public.batch_collections is
  'Junction table for pooling. Trace DTN through collections.donor_id, CTN through collections.ctn.';

-- Keep batch.total_volume_ml in sync with batch_collections rows
create or replace function public.refresh_batch_total_volume()
returns trigger
language plpgsql
as $$
declare
  target uuid;
begin
  target := case tg_op when 'DELETE' then old.batch_id else new.batch_id end;

  update public.batches
  set    total_volume_ml = coalesce(
    (select sum(volume_ml) from public.batch_collections where batch_id = target), 0
  )
  where  id = target;

  if tg_op = 'UPDATE' and old.batch_id is distinct from new.batch_id then
    update public.batches
    set    total_volume_ml = coalesce(
      (select sum(volume_ml) from public.batch_collections where batch_id = old.batch_id), 0
    )
    where  id = old.batch_id;
  end if;

  return case tg_op when 'DELETE' then old else new end;
end;
$$;

create trigger batch_collections_refresh_batch_total
after insert or update or delete on public.batch_collections
for each row execute function public.refresh_batch_total_volume();

-- ---------------------------------------------------------------------------
-- Lab results
-- ---------------------------------------------------------------------------

create table public.lab_results (
  id                uuid           primary key default gen_random_uuid(),
  batch_id          uuid           not null references public.batches(id) on delete restrict,
  stage             text           not null check (stage in ('pre_pasteurization', 'post_pasteurization')),
  sample_volume_ml  numeric(5,2)   not null check (sample_volume_ml > 0 and sample_volume_ml <= 5),
  sent_to_lab_at    timestamptz    not null,
  expected_result_at timestamptz   not null,
  result            text           not null default 'pending'
                                   check (result in ('pending', 'passed', 'failed')),
  result_received_at timestamptz,
  recorded_by       uuid           references public.profiles(id) on delete restrict,
  recorded_by_name  text,                -- free-text name when recorded_by UUID is unavailable
  notes             text,
  created_at        timestamptz    not null default now(),
  updated_at        timestamptz    not null default now(),
  constraint lab_result_date_required check (
    result = 'pending' or result_received_at is not null
  )
);

-- One pending result per stage per batch (prevents duplicate pending entries)
create unique index lab_results_one_pending_per_stage_idx
  on public.lab_results(batch_id, stage)
  where result = 'pending';

create index lab_results_batch_stage_idx on public.lab_results(batch_id, stage);
create index lab_results_result_idx      on public.lab_results(result);

-- Auto-compute expected_result_at as sent_to_lab_at + 14 days (City Hall turnaround)
create or replace function public.set_lab_expected_result_at()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' then
    if new.expected_result_at is null then
      new.expected_result_at := new.sent_to_lab_at + interval '14 days';
    end if;
  elsif new.expected_result_at is null
     or new.sent_to_lab_at is distinct from old.sent_to_lab_at then
    new.expected_result_at := new.sent_to_lab_at + interval '14 days';
  end if;
  return new;
end;
$$;

create trigger lab_results_set_expected_result_at
before insert or update of sent_to_lab_at, expected_result_at on public.lab_results
for each row execute function public.set_lab_expected_result_at();

create trigger lab_results_set_updated_at
before update on public.lab_results
for each row execute function public.set_updated_at();

-- Advance batch status based on lab result
create or replace function public.apply_lab_result_to_batch()
returns trigger
language plpgsql
as $$
begin
  case
    when new.stage = 'pre_pasteurization'  and new.result = 'pending' then
      update public.batches set status = 'pre_testing'
        where id = new.batch_id and status = 'raw';
    when new.stage = 'pre_pasteurization'  and new.result = 'passed'  then
      update public.batches set status = 'pre_test_passed'
        where id = new.batch_id;
    when new.stage = 'pre_pasteurization'  and new.result = 'failed'  then
      update public.batches set status = 'discarded',
        discarded_reason = 'failed pre-pasteurization lab test'
        where id = new.batch_id;
    when new.stage = 'post_pasteurization' and new.result = 'pending' then
      update public.batches set status = 'post_testing'
        where id = new.batch_id and status = 'pasteurized';
    when new.stage = 'post_pasteurization' and new.result = 'passed'  then
      update public.batches set status = 'ready'
        where id = new.batch_id;
    when new.stage = 'post_pasteurization' and new.result = 'failed'  then
      update public.batches set status = 'discarded',
        discarded_reason = 'failed post-pasteurization lab test'
        where id = new.batch_id;
    else null;
  end case;
  return new;
end;
$$;

create trigger lab_results_apply_batch_status
after insert or update of stage, result on public.lab_results
for each row execute function public.apply_lab_result_to_batch();

-- ---------------------------------------------------------------------------
-- Pasteurization
-- ---------------------------------------------------------------------------

create table public.pasteurization_records (
  id               uuid           primary key default gen_random_uuid(),
  batch_id         uuid           not null references public.batches(id) on delete restrict,
  pasteurized_at   timestamptz    not null,
  temperature_c    numeric(4,1)   not null check (temperature_c between 60.0 and 65.0),
  duration_minutes integer        not null check (duration_minutes between 25 and 40),
  performed_by     uuid           references public.profiles(id) on delete restrict,
  notes            text,
  created_at       timestamptz    not null default now(),
  updated_at       timestamptz    not null default now(),
  constraint one_pasteurization_per_batch unique (batch_id)
);

create trigger pasteurization_records_set_updated_at
before update on public.pasteurization_records
for each row execute function public.set_updated_at();

-- Guard: batch must be pre_test_passed; advance to pasteurized
create or replace function public.apply_pasteurization_to_batch()
returns trigger
language plpgsql
as $$
begin
  if not exists (
    select 1 from public.batches
    where id = new.batch_id and status = 'pre_test_passed'
  ) then
    raise exception 'batch % must be pre_test_passed before pasteurization', new.batch_id;
  end if;

  update public.batches set status = 'pasteurized' where id = new.batch_id;
  return new;
end;
$$;

create trigger pasteurization_records_apply_batch_status
after insert on public.pasteurization_records
for each row execute function public.apply_pasteurization_to_batch();

-- ---------------------------------------------------------------------------
-- Bottles
-- ---------------------------------------------------------------------------

create table public.bottles (
  id                   uuid        primary key default gen_random_uuid(),
  bottle_number_seq    bigint      generated by default as identity unique,
  bottle_number        text        generated always as ('BTL-' || lpad(bottle_number_seq::text, 6, '0')) stored unique,
  batch_id             uuid        not null references public.batches(id) on delete restrict,
  volume_ml            integer     not null check (volume_ml > 0),
  remaining_volume_ml  integer     not null check (remaining_volume_ml >= 0),
  status               text        not null default 'available'
                                   check (status in ('available', 'reserved', 'dispensed', 'discarded', 'expired')),
  storage_location     text,
  expires_at           timestamptz,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),
  constraint bottle_remaining_not_more_than_volume check (remaining_volume_ml <= volume_ml),
  constraint dispensed_bottle_has_no_remaining_volume check (
    status <> 'dispensed' or remaining_volume_ml = 0
  )
);

create index bottles_batch_idx on public.bottles(batch_id);
create index bottles_fifo_idx  on public.bottles(status, expires_at, created_at);

create trigger bottles_set_updated_at
before update on public.bottles
for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Beneficiaries, inquiries, pricing, dispensing, notifications
-- ---------------------------------------------------------------------------

create table public.beneficiaries (
  id               uuid        primary key default gen_random_uuid(),
  guardian_name    text        not null,
  baby_name        text        not null,
  hospital         text,
  nicu_eligible    boolean     not null default false,
  contact_number   text,
  contact_email    text,
  age_of_baby_days integer     check (age_of_baby_days is null or age_of_baby_days >= 0),
  notes            text,
  created_by       uuid        references public.profiles(id) on delete restrict,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  constraint beneficiary_has_contact check (
    contact_number is not null or contact_email is not null
  ),
  constraint beneficiary_email_normalized check (
    contact_email is null or contact_email = lower(contact_email)
  )
);

create index beneficiaries_nicu_idx           on public.beneficiaries(nicu_eligible);
create index beneficiaries_guardian_search_idx on public.beneficiaries using gin (to_tsvector('simple', guardian_name));
create index beneficiaries_baby_search_idx     on public.beneficiaries using gin (to_tsvector('simple', baby_name));

create trigger beneficiaries_set_updated_at
before update on public.beneficiaries
for each row execute function public.set_updated_at();

create table public.inquiries (
  id                  uuid        primary key default gen_random_uuid(),
  beneficiary_id      uuid        not null references public.beneficiaries(id) on delete restrict,
  inquiry_type        text        not null check (inquiry_type in ('walk_in', 'hotline_call')),
  status              text        not null default 'waiting'
                                  check (status in ('waiting', 'notified', 'fulfilled', 'cancelled')),
  requested_volume_ml integer     check (requested_volume_ml is null or requested_volume_ml > 0),
  nicu_confirmed      boolean     not null default false,
  requested_at        timestamptz not null default now(),
  -- Timestamps are auto-set by set_inquiry_status_timestamps trigger on status change.
  -- The frontend does not need to supply them.
  notified_at         timestamptz,
  fulfilled_at        timestamptz,
  cancelled_at        timestamptz,
  handled_by          uuid        references public.profiles(id) on delete restrict,
  notes               text,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  constraint waiting_list_requires_nicu check (
    status not in ('waiting', 'notified') or nicu_confirmed = true
  )
);

create index inquiries_fifo_idx        on public.inquiries(status, requested_at);
create index inquiries_beneficiary_idx on public.inquiries(beneficiary_id);

create trigger inquiries_set_updated_at
before update on public.inquiries
for each row execute function public.set_updated_at();

-- Auto-set status timestamps so the frontend only needs to set status
create or replace function public.set_inquiry_status_timestamps()
returns trigger
language plpgsql
as $$
begin
  if new.status is distinct from old.status then
    if new.status = 'notified'  and new.notified_at  is null then new.notified_at  := now(); end if;
    if new.status = 'fulfilled' and new.fulfilled_at is null then new.fulfilled_at := now(); end if;
    if new.status = 'cancelled' and new.cancelled_at is null then new.cancelled_at := now(); end if;
  end if;
  return new;
end;
$$;

create trigger inquiries_set_status_timestamps
before update of status on public.inquiries
for each row execute function public.set_inquiry_status_timestamps();

create table public.pricing_config (
  id                    uuid           primary key default gen_random_uuid(),
  price_per_ml          numeric(8,2)   not null check (price_per_ml >= 0),
  bottle_deposit_amount numeric(8,2)   not null default 0 check (bottle_deposit_amount >= 0),
  effective_from        timestamptz    not null default now(),
  effective_to          timestamptz,
  created_by            uuid           references public.profiles(id) on delete restrict,
  created_at            timestamptz    not null default now(),
  constraint pricing_effective_range check (
    effective_to is null or effective_to > effective_from
  )
);

create unique index pricing_config_one_current_idx
  on public.pricing_config((effective_to is null))
  where effective_to is null;

-- Default price: 2.00 PHP/mL, 0 deposit
insert into public.pricing_config (price_per_ml, bottle_deposit_amount, effective_from)
values (2.00, 0.00, now())
on conflict do nothing;

create table public.dispensing_records (
  id                          uuid           primary key default gen_random_uuid(),
  beneficiary_id              uuid           not null references public.beneficiaries(id) on delete restrict,
  inquiry_id                  uuid           references public.inquiries(id) on delete restrict,
  pricing_config_id           uuid           references public.pricing_config(id) on delete restrict,
  status                      text           not null default 'draft'
                                             check (status in ('draft', 'confirmed', 'cancelled')),
  volume_ml                   integer        not null check (volume_ml > 0),
  fee_per_ml                  numeric(8,2)   not null default 2.00 check (fee_per_ml >= 0),
  bottle_deposit_amount       numeric(8,2)   not null default 0 check (bottle_deposit_amount >= 0),
  total_fee                   numeric(10,2)  generated always as
                                             ((volume_ml * fee_per_ml) + bottle_deposit_amount) stored,
  deposit_paid                boolean        not null default false,
  clinical_abstract_verified  boolean        not null default false,
  prescription_verified       boolean        not null default false,
  cooler_with_ice_verified    boolean        not null default false,
  dispensed_by                uuid           references public.profiles(id) on delete restrict,
  dispensed_at                timestamptz,
  cancelled_at                timestamptz,
  notes                       text,
  created_at                  timestamptz    not null default now(),
  updated_at                  timestamptz    not null default now(),
  -- All clinical gates must be passed and dispatcher identified before confirming
  constraint confirmed_dispensing_requires_gate check (
    status <> 'confirmed'
    or (
      clinical_abstract_verified = true
      and prescription_verified  = true
      and cooler_with_ice_verified = true
      and dispensed_by  is not null
      and dispensed_at  is not null
    )
  ),
  constraint cancelled_dispensing_requires_timestamp check (
    status <> 'cancelled' or cancelled_at is not null
  )
);

create index dispensing_records_beneficiary_idx  on public.dispensing_records(beneficiary_id);
create index dispensing_records_inquiry_idx      on public.dispensing_records(inquiry_id);
create index dispensing_records_dispensed_at_idx on public.dispensing_records(dispensed_at);

create trigger dispensing_records_set_updated_at
before update on public.dispensing_records
for each row execute function public.set_updated_at();

create table public.dispensing_items (
  id                   uuid        primary key default gen_random_uuid(),
  dispensing_record_id uuid        not null references public.dispensing_records(id) on delete restrict,
  bottle_id            uuid        not null references public.bottles(id) on delete restrict,
  volume_ml            integer     not null check (volume_ml > 0),
  created_at           timestamptz not null default now(),
  constraint dispensing_items_unique_bottle_per_record unique (dispensing_record_id, bottle_id)
);

create index dispensing_items_bottle_idx on public.dispensing_items(bottle_id);

create table public.email_notifications (
  id              uuid        primary key default gen_random_uuid(),
  inquiry_id      uuid        references public.inquiries(id) on delete restrict,
  beneficiary_id  uuid        not null references public.beneficiaries(id) on delete restrict,
  trigger_event   text        not null check (
                              trigger_event in ('milk_available', 'dispensing_confirmation', 'status_update')
                              ),
  recipient_email text        not null,
  subject         text        not null,
  body            text        not null,
  status          text        not null default 'queued'
                              check (status in ('queued', 'sent', 'failed', 'cancelled')),
  queued_at       timestamptz not null default now(),
  sent_at         timestamptz,
  failed_at       timestamptz,
  error_message   text,
  created_at      timestamptz not null default now(),
  constraint email_notification_status_timestamp_alignment check (
    (status <> 'sent'   or sent_at   is not null)
    and (status <> 'failed' or failed_at is not null)
  ),
  constraint email_notification_email_normalized check (
    recipient_email = lower(recipient_email)
  )
);

create index email_notifications_status_idx      on public.email_notifications(status, queued_at);
create index email_notifications_beneficiary_idx on public.email_notifications(beneficiary_id);

-- ---------------------------------------------------------------------------
-- Audit trail
-- ---------------------------------------------------------------------------

create table public.audit_logs (
  id          uuid        primary key default gen_random_uuid(),
  table_name  text        not null,
  record_id   uuid,
  action      text        not null check (action in ('insert', 'update', 'delete')),
  changed_by  uuid        references public.profiles(id) on delete set null,
  changed_at  timestamptz not null default now(),
  old_row     jsonb,
  new_row     jsonb
);

create index audit_logs_table_record_idx on public.audit_logs(table_name, record_id);
create index audit_logs_changed_at_idx   on public.audit_logs(changed_at);

create or replace function public.write_audit_log()
returns trigger
language plpgsql security definer
set search_path = public
as $$
declare
  affected_id  uuid;
  old_payload  jsonb;
  new_payload  jsonb;
begin
  if tg_op = 'INSERT' then
    affected_id := new.id; old_payload := null;        new_payload := to_jsonb(new);
  elsif tg_op = 'UPDATE' then
    affected_id := new.id; old_payload := to_jsonb(old); new_payload := to_jsonb(new);
  elsif tg_op = 'DELETE' then
    affected_id := old.id; old_payload := to_jsonb(old); new_payload := null;
  end if;

  insert into public.audit_logs (table_name, record_id, action, changed_by, old_row, new_row)
  values (tg_table_name, affected_id, lower(tg_op), auth.uid(), old_payload, new_payload);

  return case tg_op when 'DELETE' then old else new end;
end;
$$;

create trigger audit_profiles               after insert or update or delete on public.profiles               for each row execute function public.write_audit_log();
create trigger audit_donors                 after insert or update or delete on public.donors                 for each row execute function public.write_audit_log();
create trigger audit_donor_screenings       after insert or update or delete on public.donor_screenings       for each row execute function public.write_audit_log();
create trigger audit_collections            after insert or update or delete on public.collections            for each row execute function public.write_audit_log();
create trigger audit_batches                after insert or update or delete on public.batches                for each row execute function public.write_audit_log();
create trigger audit_lab_results            after insert or update or delete on public.lab_results            for each row execute function public.write_audit_log();
create trigger audit_pasteurization_records after insert or update or delete on public.pasteurization_records for each row execute function public.write_audit_log();
create trigger audit_bottles                after insert or update or delete on public.bottles                for each row execute function public.write_audit_log();
create trigger audit_beneficiaries          after insert or update or delete on public.beneficiaries          for each row execute function public.write_audit_log();
create trigger audit_inquiries              after insert or update or delete on public.inquiries              for each row execute function public.write_audit_log();
create trigger audit_pricing_config         after insert or update or delete on public.pricing_config         for each row execute function public.write_audit_log();
create trigger audit_dispensing_records     after insert or update or delete on public.dispensing_records     for each row execute function public.write_audit_log();
create trigger audit_dispensing_items       after insert or update or delete on public.dispensing_items       for each row execute function public.write_audit_log();
create trigger audit_email_notifications    after insert or update or delete on public.email_notifications    for each row execute function public.write_audit_log();

-- ---------------------------------------------------------------------------
-- Derived reporting views (used by Dashboard)
-- ---------------------------------------------------------------------------

-- Waitlist ordered by FIFO for NICU-confirmed inquiries
create view public.waitlist_fifo
with (security_invoker = true) as
select
  i.id             as inquiry_id,
  i.beneficiary_id,
  be.guardian_name,
  be.baby_name,
  be.contact_email,
  i.requested_volume_ml,
  i.requested_at
from  public.inquiries i
join  public.beneficiaries be on be.id = i.beneficiary_id
where i.status = 'waiting'
  and i.nicu_confirmed = true
order by i.requested_at;

-- Monthly collection volume by program for the dashboard chart
create view public.collection_unit_report_base
with (security_invoker = true) as
select
  c.program,
  date_trunc('month', c.collected_at)::date as report_month,
  count(*)                                   as collection_count,
  sum(c.volume_ml)                           as raw_collected_ml,
  coalesce(sum(bc.volume_ml) filter (where b.status = 'discarded'), 0)               as discarded_ml,
  coalesce(sum(bc.volume_ml) filter (where b.status in ('ready', 'dispensed')), 0)   as cleared_for_use_ml
from  public.collections c
left  join public.batch_collections bc on bc.collection_id = c.id
left  join public.batches b            on b.id = bc.batch_id
group by c.program, date_trunc('month', c.collected_at)::date;

-- ---------------------------------------------------------------------------
-- Row-Level Security
-- ---------------------------------------------------------------------------

alter table public.profiles              enable row level security;
alter table public.donors                enable row level security;
alter table public.donor_screenings      enable row level security;
alter table public.collections           enable row level security;
alter table public.batches               enable row level security;
alter table public.batch_collections     enable row level security;
alter table public.lab_results           enable row level security;
alter table public.pasteurization_records enable row level security;
alter table public.bottles               enable row level security;
alter table public.beneficiaries         enable row level security;
alter table public.inquiries             enable row level security;
alter table public.pricing_config        enable row level security;
alter table public.dispensing_records    enable row level security;
alter table public.dispensing_items      enable row level security;
alter table public.email_notifications   enable row level security;
alter table public.audit_logs            enable row level security;

-- Profiles: read own or any if admin; write only by admin
create policy profiles_read        on public.profiles for select using (id = auth.uid() or public.current_profile_is_admin());
create policy profiles_admin_write on public.profiles for all    using (public.current_profile_is_admin()) with check (public.current_profile_is_admin());

-- All remaining tables: staff (which includes admin) can read and write
create policy staff_select_donors                on public.donors                for select using (public.current_profile_is_staff());
create policy staff_insert_donors                on public.donors                for insert with check (public.current_profile_is_staff());
create policy staff_update_donors                on public.donors                for update using (public.current_profile_is_staff()) with check (public.current_profile_is_staff());
create policy admin_delete_donors                on public.donors                for delete using (public.current_profile_is_admin());

create policy staff_select_donor_screenings      on public.donor_screenings      for select using (public.current_profile_is_staff());
create policy staff_insert_donor_screenings      on public.donor_screenings      for insert with check (public.current_profile_is_staff());
create policy staff_update_donor_screenings      on public.donor_screenings      for update using (public.current_profile_is_staff()) with check (public.current_profile_is_staff());

create policy staff_select_collections           on public.collections           for select using (public.current_profile_is_staff());
create policy staff_insert_collections           on public.collections           for insert with check (public.current_profile_is_staff());
create policy staff_update_collections           on public.collections           for update using (public.current_profile_is_staff()) with check (public.current_profile_is_staff());

create policy staff_select_batches               on public.batches               for select using (public.current_profile_is_staff());
create policy staff_insert_batches               on public.batches               for insert with check (public.current_profile_is_staff());
create policy staff_update_batches               on public.batches               for update using (public.current_profile_is_staff()) with check (public.current_profile_is_staff());

create policy staff_select_batch_collections     on public.batch_collections     for select using (public.current_profile_is_staff());
create policy staff_insert_batch_collections     on public.batch_collections     for insert with check (public.current_profile_is_staff());

create policy staff_select_lab_results           on public.lab_results           for select using (public.current_profile_is_staff());
create policy staff_insert_lab_results           on public.lab_results           for insert with check (public.current_profile_is_staff());
create policy staff_update_lab_results           on public.lab_results           for update using (public.current_profile_is_staff()) with check (public.current_profile_is_staff());

create policy staff_select_pasteurization_records on public.pasteurization_records for select using (public.current_profile_is_staff());
create policy staff_insert_pasteurization_records on public.pasteurization_records for insert with check (public.current_profile_is_staff());

create policy staff_select_bottles               on public.bottles               for select using (public.current_profile_is_staff());
create policy staff_insert_bottles               on public.bottles               for insert with check (public.current_profile_is_staff());
create policy staff_update_bottles               on public.bottles               for update using (public.current_profile_is_staff()) with check (public.current_profile_is_staff());

create policy staff_select_beneficiaries         on public.beneficiaries         for select using (public.current_profile_is_staff());
create policy staff_insert_beneficiaries         on public.beneficiaries         for insert with check (public.current_profile_is_staff());
create policy staff_update_beneficiaries         on public.beneficiaries         for update using (public.current_profile_is_staff()) with check (public.current_profile_is_staff());
create policy admin_delete_beneficiaries         on public.beneficiaries         for delete using (public.current_profile_is_admin());

create policy staff_select_inquiries             on public.inquiries             for select using (public.current_profile_is_staff());
create policy staff_insert_inquiries             on public.inquiries             for insert with check (public.current_profile_is_staff());
create policy staff_update_inquiries             on public.inquiries             for update using (public.current_profile_is_staff()) with check (public.current_profile_is_staff());

create policy staff_select_pricing_config        on public.pricing_config        for select using (public.current_profile_is_staff());
create policy admin_manage_pricing_config        on public.pricing_config        for all    using (public.current_profile_is_admin()) with check (public.current_profile_is_admin());

create policy staff_select_dispensing_records    on public.dispensing_records    for select using (public.current_profile_is_staff());
create policy staff_insert_dispensing_records    on public.dispensing_records    for insert with check (public.current_profile_is_staff());
create policy staff_update_dispensing_records    on public.dispensing_records    for update using (public.current_profile_is_staff()) with check (public.current_profile_is_staff());

create policy staff_select_dispensing_items      on public.dispensing_items      for select using (public.current_profile_is_staff());
create policy staff_insert_dispensing_items      on public.dispensing_items      for insert with check (public.current_profile_is_staff());

create policy staff_select_email_notifications   on public.email_notifications   for select using (public.current_profile_is_staff());
create policy staff_insert_email_notifications   on public.email_notifications   for insert with check (public.current_profile_is_staff());
create policy staff_update_email_notifications   on public.email_notifications   for update using (public.current_profile_is_staff()) with check (public.current_profile_is_staff());

-- Audit logs: admin read only; triggers write (no client DML policy)
create policy admin_read_audit_logs on public.audit_logs for select using (public.current_profile_is_admin());

commit;
